create table public.business_submissions (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  user_id uuid not null,
  status text not null default 'pending',
  submission_data jsonb not null,
  constraint business_submissions_pkey primary key (id),
  constraint business_submissions_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;

create index IF not exists idx_business_submissions_user_id on public.business_submissions using btree (user_id) TABLESPACE pg_default;
create index IF not exists idx_business_submissions_status on public.business_submissions using btree (status) TABLESPACE pg_default;
