-- businesses table with all indexes and constraints
CREATE TABLE public.businesses (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  title text NULL,
  description text NULL,
  category_id integer NULL,
  subcategories_id integer[] NULL,
  cid text NULL,
  feature_id text NULL,
  address text NULL,
  address_info jsonb NULL,
  place_id text NULL,
  phone text NULL,
  url text NULL,
  domain text NULL,
  logo text NULL,
  main_image text NULL,
  total_photos integer NULL,
  snippet text NULL,
  latitude double precision NULL,
  longitude double precision NULL,
  is_claimed boolean NULL,
  attributes jsonb NULL,
  place_topics jsonb NULL,
  rating jsonb NULL,
  rating_distribution jsonb NULL,
  people_also_search jsonb NULL,
  work_time jsonb NULL,
  popular_times jsonb NULL,
  local_business_links jsonb NULL,
  contacts jsonb NULL,
  time_update timestamp with time zone NULL,
  check_url text NULL,
  price_level text NULL,
  hotel_rating integer NULL,
  slug text NULL,
  state text NULL,
  city text NULL,
  zip text NULL,
  county text NULL,
  rating_value numeric GENERATED ALWAYS AS (
    COALESCE(
      NULLIF(
        ((rating ->> 'value'::text))::numeric,
        null::numeric
      ),
      (0)::numeric
    )
  ) STORED NULL,
  state_lower text GENERATED ALWAYS AS (lower(state)) STORED NULL,
  city_lower text GENERATED ALWAYS AS (lower(city)) STORED NULL,
  county_lower text GENERATED ALWAYS AS (lower(county)) STORED NULL,
  slug_tsv tsvector GENERATED ALWAYS AS (to_tsvector('english'::regconfig, slug)) STORED NULL,
  geo_point geometry(Point,4326) GENERATED ALWAYS AS (
    st_setsrid(st_makepoint(longitude, latitude), 4326)
  ) STORED NULL,
  status boolean NOT NULL DEFAULT true,
  update_slug text NULL,
  claimed_by uuid NULL,
  claimed_approval boolean NULL DEFAULT false,
  remove_request uuid NULL,
  deleted_at timestamp with time zone NULL,
  CONSTRAINT businesses__pkey PRIMARY KEY (id),
  CONSTRAINT businesses__slug_key UNIQUE (slug),
  CONSTRAINT businesses__category_id_fkey FOREIGN KEY (category_id) REFERENCES categories (id)
)
WITH (
  parallel_workers = 4,
  autovacuum_vacuum_scale_factor = 0.01,
  autovacuum_analyze_scale_factor = 0.005
) TABLESPACE pg_default;

-- businesses indexes
CREATE INDEX IF NOT EXISTS idx_businesses_claimed_by ON public.businesses USING btree (claimed_by) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_deleted_at ON public.businesses USING btree (deleted_at) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS businesses_category_id_idx ON public.businesses USING btree (category_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS businesses_county_idx ON public.businesses USING btree (county) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS businesses_subcategories_id_idx ON public.businesses USING btree (subcategories_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_address ON public.businesses USING btree (address) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_address_trgm ON public.businesses USING gin (address gin_trgm_ops) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_category ON public.businesses USING btree (category_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_category_id ON public.businesses USING btree (category_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_city ON public.businesses USING btree (city) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_city_lower ON public.businesses USING btree (lower(city)) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_city_lower_new ON public.businesses USING btree (city_lower) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_county ON public.businesses USING gin (county gin_trgm_ops) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_county_category ON public.businesses USING btree (lower(county), category_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_county_lower ON public.businesses USING btree (lower(county)) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_county_lower_new ON public.businesses USING btree (county_lower) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_description_trgm ON public.businesses USING gin (description gin_trgm_ops) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_fulltext ON public.businesses USING gin (to_tsvector('english'::regconfig, ((title || ' '::text) || description))) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_geo ON public.businesses USING btree (latitude, longitude) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_geo_point ON public.businesses USING gist (geo_point) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_lat_long ON public.businesses USING btree (latitude, longitude) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_location ON public.businesses USING gist (st_setsrid(st_makepoint(longitude, latitude), 4326)) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_non_null_category_id ON public.businesses USING btree (category_id) TABLESPACE pg_default WHERE (category_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_businesses_rating ON public.businesses USING btree (((rating ->> 'value'::text))) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_rating_value ON public.businesses USING btree (rating_value DESC) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_search ON public.businesses USING gin (to_tsvector('english'::regconfig, ((title || ' '::text) || description))) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_slug ON public.businesses USING btree (slug) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_slug_status_state_county ON public.businesses USING btree (slug, status, state_lower, county_lower) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_slug_tsv ON public.businesses USING gin (slug_tsv) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_state ON public.businesses USING btree (state) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_state_city ON public.businesses USING btree (state, city) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_state_city_zip ON public.businesses USING btree (lower(state), lower(city), zip) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_state_county ON public.businesses USING btree (lower(state), lower(county)) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_state_county_category ON public.businesses USING btree (lower(state), lower(county), category_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_state_county_city_lower ON public.businesses USING btree (state_lower, county_lower, city_lower) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_state_county_lower ON public.businesses USING btree (state_lower, county_lower) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_state_county_rating ON public.businesses USING btree (lower(state), lower(county), rating_value) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_state_lower ON public.businesses USING btree (lower(state)) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_state_lower_new ON public.businesses USING btree (state_lower) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_status ON public.businesses USING btree (status) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_subcategories ON public.businesses USING gin (subcategories_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_text ON public.businesses USING gin (to_tsvector('english'::regconfig, ((title || ' '::text) || description))) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_title_trgm ON public.businesses USING gin (title gin_trgm_ops) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_votes_count ON public.businesses USING btree ((((rating ->> 'votes_count'::text))::integer)) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_zip ON public.businesses USING btree (zip) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_category_id ON public.businesses USING btree (category_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_update_slug ON public.businesses USING btree (update_slug) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_businesses_update_slug_state_county ON public.businesses USING btree (update_slug, state_lower) TABLESPACE pg_default WHERE (status = true);
CREATE INDEX IF NOT EXISTS idx_businesses_slug_state_county ON public.businesses USING btree (slug, state_lower) TABLESPACE pg_default WHERE (status = true);

-- categories table
CREATE TABLE public.categories (
  id serial NOT NULL,
  name text NOT NULL,
  featured boolean NOT NULL DEFAULT false,
  CONSTRAINT categories_pkey PRIMARY KEY (id),
  CONSTRAINT categories_name_key UNIQUE (name)
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS categories_featured_idx ON public.categories USING btree (featured) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_categories_id ON public.categories USING btree (id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_categories_name ON public.categories USING btree (name) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_categories_name_lower ON public.categories USING btree (lower(name)) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_categories_name_trgm ON public.categories USING gin (name gin_trgm_ops) TABLESPACE pg_default;

-- subcategories table
CREATE TABLE public.subcategories (
  id serial NOT NULL,
  category_id integer NULL,
  name text NOT NULL,
  cat_id_sub_name text NULL,
  CONSTRAINT subcategories_pkey PRIMARY KEY (id),
  CONSTRAINT subcategories_cat_id_sub_name_key UNIQUE (cat_id_sub_name),
  CONSTRAINT subcategories_category_id_fkey FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_subcategories_category_id ON public.subcategories USING btree (category_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_subcategories_name ON public.subcategories USING btree (name) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_subcategories_name_lower ON public.subcategories USING btree (lower(name)) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_subcategories_name_trgm ON public.subcategories USING gin (name gin_trgm_ops) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS subcategories_category_id_idx ON public.subcategories USING btree (category_id) TABLESPACE pg_default;

-- stateswise table
CREATE TABLE public.stateswise (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  listingsdb_id bigint NULL,
  city text NULL,
  county text NULL,
  state text NULL,
  subdivision text NULL,
  zip text NULL,
  elementaryschool text NULL,
  schooldistrict text NULL,
  highschool text NULL,
  middleschool text NULL,
  zoning text NULL,
  waterbodyname text NULL,
  zoningdescription text NULL,
  CONSTRAINT stateswise_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS stateswise_listingsdb_id_idx ON public.stateswise USING btree (listingsdb_id) TABLESPACE pg_default;

-- search_cache table
CREATE TABLE public.search_cache (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  type text NOT NULL DEFAULT 'business'::text,
  question text NOT NULL,
  extract_object jsonb NOT NULL,
  slug text NOT NULL,
  listing_pages boolean NOT NULL DEFAULT false,
  site_slug text NOT NULL DEFAULT 'baltimore'::text,
  CONSTRAINT search_cache_pkey PRIMARY KEY (id),
  CONSTRAINT search_cache_question_key UNIQUE (question)
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS search_cache_question_idx ON public.search_cache USING btree (question) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS search_cache_site_slug_idx ON public.search_cache USING btree (site_slug) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS search_cache_slug_listing_pages_idx ON public.search_cache USING btree (slug, listing_pages) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS search_cache_type_idx ON public.search_cache USING btree (type) TABLESPACE pg_default;

-- business_count_cache_table
CREATE TABLE public.business_count_cache_table (
  cache_key text NOT NULL,
  total_count integer NULL,
  last_updated timestamp with time zone NULL,
  CONSTRAINT business_count_cache_table_pkey PRIMARY KEY (cache_key)
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_business_count_cache_last_updated ON public.business_count_cache_table USING btree (last_updated) TABLESPACE pg_default;
